name: Repo Sync

on:
  workflow_dispatch:
  
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Repo-Sync.yaml'

  schedule:
    - cron: 3-53/10 * * * *

jobs:
  jd-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: smiek2221
        run: |
          bash Scripts/Sync.sh \
            https://github.com/smiek2221/scripts master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/bbbup/smiek2221
      - name: X1a0He
        run: |
          bash Scripts/Sync.sh \
            https://github.com/X1a0He/jd_scripts_fixed main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/bbbup/X1a0He
      - name: Aaron-lv
        run: |
          bash Scripts/Sync.sh \
            https://github.com/Aaron-lv/sync jd_scripts \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/bbbup/Aaron-lv
      - name: Novl24
        run: |
          bash Scripts/Sync.sh \
            https://github.com/Novl24/sync main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/bbbup/Novl24    
